laravel/fric-frac-laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('eventcategory','EventCategoryController');
Route::resource('eventtopic','EventTopicController');
Route::resource('event', 'EventController');

laravel/fric-frac-laravel/app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $fillable = [
        'name',
        'location',
        'starts',
        'ends',
        'description',
        'organiserName',
        'organiserDescription',
        'eventcategoryid',
        'eventtopicid',
    ];
}

laravel/fric-frac-laravel/app/Http/Controllers/EventController.php
<?php
/*
https://www.positronx.io/php-laravel-crud-operations-mysql-tutorial/
https://www.itsolutionstuff.com/post/laravel-7-crud-example-laravel-7-tutorial-for-beginnersexample.html
*/
namespace App\Http\Controllers;

use App\Event;
use App\EventCategory;
use App\EventTopic;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use View;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Event::all();
        return view('event.index', compact('events'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['events'] = Event::all();
        $data['eventCategories'] = EventCategory::all();
        $data['eventTopics'] = EventTopic::all();
        return view('event.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'location' => 'required',
            'starts'=> 'required',
            'ends'=> 'required',
            'description'=> 'required',
            'organiserName'=> 'required',
            'organiserDescription'=> 'required',
            'eventcategoryid'=> 'required',
            'eventtopicid'=> 'required'
        ]);
        Event::create($request->all());
        return redirect()->route('event.index')

            ->with('success', 'Event created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Event $events
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['events'] = Event::all();
        $where = array('id' => $id);
        $data['event_info'] = Event::where($where)->first();
        return view('event.readingone')->with($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Event  $events
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['events'] = Event::all();
        $where = array('id' => $id);
        $data['event_info'] = Event::where($where)->first();
        $data['eventCategories'] = EventCategory::all();
        $data['eventTopics'] = EventTopic::all();
        return view('event.editingone')->with($data);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Event  $events
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $request->validate([
            'name' => 'required',
            'location' => 'required',
            'starts'=> 'required',
            'ends'=> 'required',
            'description'=> 'required',
            'organiserName'=> 'required',
            'organiserDescription'=> 'required',
            'eventcategoryid'=> 'required',
            'eventtopicid'=> 'required'
        ]);
        $category = Event::find($id);
        $category->name = $request->get('name');
        $category->location = $request->get('location');
        $category->starts = $request->get('starts');
        $category->ends = $request->get('ends');
        $category->description = $request->get('description');
        $category->organiserName = $request->get('organiserName');
        $category->organiserDescription = $request->get('organiserDescription');
        $category->eventcategoryid = $request->get('eventcategoryid');
        $category->eventtopicid = $request->get('eventtopicid');
        $category->save();
        $events = Event::all();
        return view("event.index",compact('events'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Event  $events
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Event::find($id);
        $item -> delete();
        $events = Event::all();

        return view("event.index",compact('events'));



    }
}

laravel/fric-frac-laravel/resources/views/event/create.blade.php
@extends('layout')
@section('content')


    <section class="show-room entity">
        <form id="form" method="post" action="{{route('event.store')}}" class="detail">
            @csrf
            <nav class="command-panel">
                <h2 class="banner">Event</h2>
                <button type="submit" value="insert" name="uc" class='tile'>
                    <span class="icon-floppy-disk"></span>
                    <span class="screen-reader-text">Insert One</span>
                </button>
                <a href="{{ route('event.index') }}" class="tile">
                    <span class="icon-cross"></span>
                    <span class="screen-reader-text">Annuleren</span>
                </a>
            </nav>
            <fieldset>
                <div>
                    <label for="name">Naam</label>
                    <input type="text" required id="name" name="name" />
                    <div>
                        <!-- HIER MOET ER EEN KEUZE KUNNEN WORDEN GEMAAKT-->
                        <label for="eventtopicid">EventTopic</label>
                        <select name="eventtopicid" id="eventtopicid">
                            @foreach ($eventTopics as $item)
                                <option value="{{$item->id}}">{{$item->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div>
                        <!-- HIER MOET ER EEN KEUZE KUNNEN WORDEN GEMAAKT-->
                        <label for="eventcategoryid">EventCategory</label>
                        <select name="eventcategoryid" id="eventcategoryid">
                            @foreach ($eventCategories as $item)
                            <option value="{{$item->id}}">{{$item->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div>
                        <label for="description">EventsDescription</label>
                        <input id="description" name="description" type="text" value="" />
                    </div>
                    <div>
                        <label for="location">eventLocation</label>
                        <input id="location" name="location" type="text" value="" />
                    </div>
                    <div>
                        <label for="organiserDescription">OrganiserDescription</label>
                        <input id="organiserDescription" name="organiserDescription" type="text" value="" />
                    </div>
                    <div>
                        <label for="organiserName">OrganiserName</label>
                        <input id="organiserName" name="organiserName" type="text" value="" />
                    </div>
                    <div>
                        <label for="starts">Starts</label>
                        <input id="starts" name="starts" type="date" value="" />
                    </div>
                    <div>
                        <label for="ends">Ends</label>
                        <input id="ends" name="ends" type="date" value="" />
                    </div>
                </div>
            </fieldset>
            @if ($errors->any())
            <div class="feedback">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </div>
                @endif
        </form>
        <aside class="list">
            <table>
                <tr>
                    <th></th>
                    <th>Naam</th>
                </tr>
                @foreach ($events as $item)
                    <tr>
                        <td>
                            <a href="{{ route('event.show',$item->id)}}">
                                <span class="icon-arrow-right"></span>
                                <span class="screen-reader-text">ReadingOne</span></a>
                        </td>
                        <td>{{$item->name }}</td>

                    </tr>
                @endforeach
            </table>
        </aside>
    </section>






@endsection

laravel/fric-frac-laravel/resources/views/event/editingone.blade.php
@extends('layout')
@section('content')




    <section class="show-room entity">
        <form id="form" method="post" action="{{ route('event.update',$event_info->id) }}" class="detail">
            @csrf
            @method('PATCH')
            <nav class="command-panel">
                <h2 class="banner">Event</h2>
                <button type="submit" value="insert" name="uc" class='tile'>
                    <span class="icon-floppy-disk"></span>
                    <span class="screen-reader-text">Update One</span>
                </button>
                <a href="{{ route('event.index') }}" class="tile">
                    <span class="icon-cross"></span>
                    <span class="screen-reader-text">Annuleren</span>
                </a>
            </nav>
            <fieldset>
                <div>
                    <label for="name">Naam</label>
                    <input type="text" required id="name" value="{{$event_info->name}}" name="name" />
                    <div>
                        <!-- HIER MOET ER EEN KEUZE KUNNEN WORDEN GEMAAKT-->
                        <label for="eventtopicid">EventTopic</label>
                        <select name="eventtopicid" id="eventtopicid">
                            @foreach ($eventTopics as $item)
                                @if($item->id == $event_info->eventtopicid)
                                    <option value="{{$item->id}}" selected>{{$item->name}}</option>
                                @else
                                    <option value="{{$item->id}}">{{$item->name}}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                    <div>
                        <!-- HIER MOET ER EEN KEUZE KUNNEN WORDEN GEMAAKT-->
                        <label for="eventcategoryid">EventCategory</label>
                        <select name="eventcategoryid" id="eventcategoryid">
                            @foreach ($eventCategories as $item)
                                @if($item->id == $event_info->eventcategoryid)
                                    <option value="{{$item->id}}" selected>{{$item->name}}</option>
                                @else
                                    <option value="{{$item->id}}">{{$item->name}}</option>
                                    @endif

                            @endforeach
                        </select>
                    </div>
                    <div>
                        <label for="description">EventsDescription</label>
                        <input id="description" name="description" type="text" value="{{$event_info->description}}" />
                    </div>
                    <div>
                        <label for="location">eventLocation</label>
                        <input id="location" name="location" type="text" value="{{$event_info->location}}" />
                    </div>
                    <div>
                        <label for="organiserDescription">OrganiserDescription</label>
                        <input id="organiserDescription" name="organiserDescription" type="text" value="{{$event_info->organiserDescription}}" />
                    </div>
                    <div>
                        <label for="organiserName">OrganiserName</label>
                        <input id="organiserName" name="organiserName" type="text" value="{{$event_info->organiserName}}" />
                    </div>
                    <div>
                        <label for="starts">Starts</label>
                        <input id="starts" name="starts" type="date" value="{{$event_info->starts}}" />
                    </div>
                    <div>
                        <label for="ends">Ends</label>
                        <input id="ends" name="ends" type="date" value="{{$event_info->ends}}" />
                    </div>
                </div>
            </fieldset>
            <div class="feedback">
            </div>
        </form>
        <aside class="list">
            <table>
                <tr>
                    <th></th>
                    <th>Naam</th>
                </tr>
                @foreach ($events as $item)
                    <tr>
                        <td>
                            <a href="{{ route('event.show',$item->id)}}">
                                <span class="icon-arrow-right"></span>
                                <span class="screen-reader-text">ReadingOne</span></a>
                        </td>
                        <td>{{$item->name }}</td>

                    </tr>
                @endforeach
            </table>
        </aside>
    </section>



    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

@endsection

laravel/fric-frac-laravel/resources/views/event/index.blade.php
@extends('layout')
@section('content')
    <section class="show-room entity">
        <div class="detail">
            <nav class="command-panel">
                <h2 class="banner">Event</h2>
                <a href="{{ route('event.create') }}" class="tile">
                    <span class="icon-plus"></span>
                    <span class="screen-reader-text">InsertingOne</span>
                </a>
            </nav>
            <fieldset></fieldset>
            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif
        </div>
        <aside class="list">
            <table>
                <tr>
                    <th></th>
                    <th>Naam</th>
                </tr>
                @foreach ($events as $item)
                <tr>
                    <td>
                        <a href="{{ route('event.show',$item->id)}}">
                            <span class="icon-arrow-right"></span>
                            <span class="screen-reader-text">ReadingOne</span></a>
                    </td>
                    <td>{{$item->name }}</td>

                </tr>
                @endforeach
            </table>
        </aside>
    </section>
@endsection

laravel/fric-frac-laravel/resources/views/event/readingone.blade.php
@extends('layout')
@section('content')

    <section class="show-room entity">
        <form id="form" method="post" action="{{ route('event.destroy', $event_info->id)}}" class="detail">
            @csrf
            @method('DELETE')
            <nav class="command-panel">
                <h2 class="banner">Event</h2>
                <a href="{{ route('event.edit',$event_info->id)}}" class="tile">
                    <span class="icon-pencil"></span>
                    <span class="screen-reader-text">Updating One</span>
                </a>
                <a href="{{ route('event.create') }}" class="tile">
                    <span class="icon-plus"></span>
                    <span class="screen-reader-text">Inserting One</span>
                </a>
                <button href="{{ route('event.destroy',$event_info->id)}}" class="tile">
                    <span class="icon-bin"></span>
                    <span class="screen-reader-text">Delete One</span>
                </button>
                <a href="{{ route('event.index') }}" class="tile">
                    <span class="icon-cross"></span>
                    <span class="screen-reader-text">Annuleren</span>
                </a>
            </nav>
            <fieldset>
                <div>
                    <label for="Name">Naam:</label>
                    <span>{{ $event_info->name }}</span>
                </div>
            </fieldset>
            <div class="feedback"></div>
        </form>
        <aside class="list">
            <table>
                <tr>
                    <th></th>
                    <th>Naam</th>
                </tr>
                @foreach ($events as $item)
                    <tr>
                        <td>
                            <a href="{{ route('event.show',$item->id)}}">
                                <span class="icon-arrow-right"></span>
                                <span class="screen-reader-text">ReadingOne</span></a>
                        </td>
                        <td>{{$item->name }}</td>

                    </tr>
                @endforeach
            </table>
        </aside>
    </section>


@endsection