laravel/fric-frac-laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('eventcategory','EventCategoryController');
Route::resource('eventtopic','EventTopicController');
Route::resource('event', 'EventController');

laravel/fric-frac-laravel/app/EventTopic.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EventTopic extends Model
{
    protected $fillable = [
        'name'
    ];
}

laravel/fric-frac-laravel/app/Http/Controllers/EventTopicController.php
<?php
/*
https://www.positronx.io/php-laravel-crud-operations-mysql-tutorial/
https://www.itsolutionstuff.com/post/laravel-7-crud-example-laravel-7-tutorial-for-beginnersexample.html
*/
namespace App\Http\Controllers;

use App\EventCategory;
use App\EventTopic;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use View;

class EventTopicController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $eventtopics = EventTopic::all();
        return view('eventtopic.index', compact('eventtopics'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['eventTopics'] = EventTopic::all();
        return view('eventtopic.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ]);
        EventTopic::create($request->all());
        return redirect()->route('eventtopic.index')

            ->with('success', 'Eventtopic created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\EventTopic $eventTopic
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['eventTopics'] = EventTopic::all();
        $where = array('id' => $id);
        $data['eventtopic_info'] = EventTopic::where($where)->first();
        return view('eventtopic.readingone')->with($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\EventTopic  $eventTopic
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['eventTopics'] = EventTopic::all();
        $where = array('id' => $id);
        $data['eventtopic_info'] = EventTopic::where($where)->first();
        return view('eventtopic.editingone')->with($data);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\EventTopic  $eventTopic
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $request->validate([
            'name' => 'required',
        ]);
        $category = EventTopic::find($id);
        $category->name = $request->get('name');
        $category->save();
        $eventtopics = EventTopic::all();
        return view("eventtopic.index",compact('eventtopics'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\EventTopic  $eventTopic
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = EventTopic::find($id);
        $item -> delete();
        $eventtopics = EventTopic::all();

        return view("eventtopic.index",compact('eventtopics'));



    }
}

laravel/fric-frac-laravel/resources/views/eventtopic/create.blade.php
@extends('layout')
@section('content')


    <section class="show-room entity">
        <form id="form" method="post" action="{{route('eventtopic.store')}}" class="detail">
            @csrf
            <nav class="command-panel">
                <h2 class="banner">EventTopic</h2>
                <button type="submit" value="insert" name="uc" class='tile'>
                    <span class="icon-floppy-disk"></span>
                    <span class="screen-reader-text">Insert One</span>
                </button>
                <a href="{{ route('eventtopic.index') }}" class="tile">
                    <span class="icon-cross"></span>
                    <span class="screen-reader-text">Annuleren</span>
                </a>
            </nav>
            <fieldset>
                <div>
                    <label for="name">Naam</label>
                    <input type="text" required id="name" name="name" />
                </div>
            </fieldset>
            @if ($errors->any())
                <div class="feedback">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </div>
            @endif
        </form>
        <aside class="list">
            <table>
                <tr>
                    <th></th>
                    <th>Naam</th>
                </tr>
                @foreach ($eventTopics as $item)
                    <tr>
                        <td>
                            <a href="{{ route('eventtopic.show',$item->id)}}">
                                <span class="icon-arrow-right"></span>
                                <span class="screen-reader-text">ReadingOne</span></a>
                        </td>
                        <td>{{$item->name }}</td>

                    </tr>
                @endforeach
            </table>
        </aside>
    </section>






@endsection

laravel/fric-frac-laravel/resources/views/eventtopic/editingone.blade.php
@extends('layout')
@section('content')




    <section class="show-room entity">
        <form id="form" method="post" action="{{ route('eventtopic.update',$eventtopic_info->id) }}" class="detail">
            @csrf
            @method('PATCH')
            <nav class="command-panel">
                <h2 class="banner">EventTopic</h2>
                <button type="submit" value="insert" name="uc" class='tile'>
                    <span class="icon-floppy-disk"></span>
                    <span class="screen-reader-text">Update One</span>
                </button>
                <a href="{{ route('eventtopic.index') }}" class="tile">
                    <span class="icon-cross"></span>
                    <span class="screen-reader-text">Annuleren</span>
                </a>
            </nav>
            <fieldset>
                <input type="hidden" id="Id" name="Id" value="{{$eventtopic_info->id}}" />
                <div>
                    <label for="name">Naam</label>
                    <input id="name" name="name" type="text" value={{$eventtopic_info->name}} required />
                </div>
            </fieldset>
            <div class="feedback">
            </div>
        </form>
        <aside class="list">
            <table>
                <tr>
                    <th></th>
                    <th>Naam</th>
                </tr>
                @foreach ($eventTopics as $item)
                    <tr>
                        <td>
                            <a href="{{ route('eventtopic.show',$item->id)}}">
                                <span class="icon-arrow-right"></span>
                                <span class="screen-reader-text">ReadingOne</span></a>
                        </td>
                        <td>{{$item->name }}</td>

                    </tr>
                @endforeach
            </table>
        </aside>
    </section>



    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

@endsection

laravel/fric-frac-laravel/resources/views/eventtopic/index.blade.php
@extends('layout')
@section('content')




    <section class="show-room entity">
        <div class="detail">
            <nav class="command-panel">
                <h2 class="banner">EventTopic</h2>
                <a href="{{ route('eventtopic.create') }}" class="tile">
                    <span class="icon-plus"></span>
                    <span class="screen-reader-text">InsertingOne</span>
                </a>
            </nav>
            <fieldset></fieldset>
            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif
        </div>
        <aside class="list">
            <table>
                <tr>
                    <th></th>
                    <th>Naam</th>
                </tr>
                @foreach ($eventtopics as $item)
                    <tr>
                        <td>
                            <a href="{{ route('eventtopic.show',$item->id)}}">
                                <span class="icon-arrow-right"></span>
                                <span class="screen-reader-text">ReadingOne</span></a>
                        </td>
                        <td>{{$item->name }}</td>

                    </tr>
                @endforeach
            </table>
        </aside>
    </section>
@endsection

laravel/fric-frac-laravel/resources/views/eventtopic/readingone.blade.php
@extends('layout')
@section('content')




    <section class="show-room entity">
        <form id="form" method="post" action="{{ route('eventtopic.destroy', $eventtopic_info->id)}}" class="detail">
            @csrf
            @method('DELETE')
            <nav class="command-panel">
                <h2 class="banner">EventTopic</h2>
                <a href="{{ route('eventtopic.edit',$eventtopic_info->id)}}" class="tile">
                    <span class="icon-pencil"></span>
                    <span class="screen-reader-text">Updating One</span>
                </a>
                <a href="{{ route('eventtopic.create') }}" class="tile">
                    <span class="icon-plus"></span>
                    <span class="screen-reader-text">Inserting One</span>
                </a>
                <button href="{{ route('eventtopic.destroy',$eventtopic_info->id)}}" class="tile">
                    <span class="icon-bin"></span>
                    <span class="screen-reader-text">Delete One</span>
                </button>
                <a href="{{ route('eventtopic.index') }}" class="tile">
                    <span class="icon-cross"></span>
                    <span class="screen-reader-text">Annuleren</span>
                </a>
            </nav>
            <fieldset>
                <div>
                    <label for="Name">Naam:</label>
                    <span>{{ $eventtopic_info->name }}</span>
                </div>
            </fieldset>
            <div class="feedback"></div>
        </form>
        <aside class="list">
            <table>
                <tr>
                    <th></th>
                    <th>Naam</th>
                </tr>
                @foreach ($eventTopics as $item)
                    <tr>
                        <td>
                            <a href="{{ route('eventtopic.show',$item->id)}}">
                                <span class="icon-arrow-right"></span>
                                <span class="screen-reader-text">ReadingOne</span></a>
                        </td>
                        <td>{{$item->name }}</td>

                    </tr>
                @endforeach
            </table>
        </aside>
    </section>


@endsection